### ISSUE TITLE
White becomes Transparent

### ISSUE THREAD

**Issue by xenometal** [ShiningForceCentral/SF2BattleSpriteManager#1]
Transparency (palette index 0) and White (palette index 1) are being conflated when exporting to PNG/GIF due to both entries having identical color values.

It appears as though the tool is not using color values from the sprite data for palette index 0, but defaulting to 0x0EEE instead.

**Comment by wizardwhosaysni** [comment]
Thanks a lot for the report, fixed :
https://github.com/ShiningForceCentral/SF2BattleSpriteManager/commit/684f3ab1453daa5eea37c83d94477a009a6701a8

Fixed a long time ago while I was working on SFCD exports, I should have pushed it back then !
